1. Add the Header; Footer and so on.
easy-booking-project/easy-booking-frontend pull request #3
Opened 2021-06-12 10:25 UTC by lidachao111222

1. Add the Header. Also the react-router-dom library.
2. Add the Footer.
3. Create the signin page and signup page

Please check.

@SeanWong24 
@willwei954

2021-06-12 19:43 UTC, willwei954 commented
Use different front colours for different themes.

2021-06-13 17:32 UTC, willwei954 requested changes
inside tsconfig, change, jsx to "jsx": "react",

line 21

2021-06-13 17:41 UTC, willwei954 approved these changes

2021-06-13 17:50 UTC, SeanWong24 approved these changes

2021-06-13 17:50 UTC, merged